# Generated by Django 5.1.1 on 2024-09-09 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('job_number', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Job Number')),
                ('request_number', models.PositiveIntegerField(unique=True, verbose_name='Request Number')),
                ('reporting_date', models.DateField(verbose_name='Reporting Date')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('ward', models.CharField(max_length=100, verbose_name='Ward')),
                ('reported_by', models.CharField(max_length=100, verbose_name='Reported By')),
                ('equipment_name', models.CharField(max_length=100, verbose_name='Equipment Name')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Serial Number')),
                ('fault_reported', models.TextField(verbose_name='Fault Reported')),
                ('diagnosis', models.TextField(verbose_name='Diagnosis')),
                ('action_done', models.TextField(verbose_name='Action Done')),
                ('required_spare_parts', models.TextField(verbose_name='Required Spare Parts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Card',
                'verbose_name_plural': 'Job Cards',
                'ordering': ['-reporting_date'],
            },
        ),
    ]
