# Generated by Django 5.1.1 on 2024-09-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
