import { FunctionComponent } from "react";
import Card from "./Card";
import AboutHeader from "./AboutHeader";
import FrameComponent from "./FrameComponent";
import styles from "./CardsContainer.module.css";

export type CardsContainerType = {
  className?: string;
};

const CardsContainer: FunctionComponent<CardsContainerType> = ({
  className = "",
}) => {
  return (
    <section className={[styles.cardsContainer, className].join(" ")}>
      <Card
        propFlex="unset"
        propAlignSelf="unset"
        propWidth="354px"
        propMarginLeft="-442px"
        propMarginBottom="-546px"
        propHeight="528px"
        propPadding="unset"
        propHeight1="102px"
        propMinWidth="unset"
        propPadding1="0px 20px"
        propAlignSelf1="stretch"
        titleGoesHere="JOB CARD"
        propAlignSelf2="stretch"
        propFlex1="1"
        secondaryText="Document every step"
        propHeight2="24px"
        propDisplay="inline-block"
        propAlignSelf3="stretch"
        rectangle18="/rectangle-18@2x.png"
        propFlex2="1"
        propFlex3="1"
        loremIpsumDolorSitAmetConsecte="Document and monitor all maintenance and repair tasks, promoting accountability, timely action, and continuous operation of critical medical equipment.."
        propAlignSelf4="stretch"
        button="Create Job Card"
        commonButtonBoxShadow="unset"
        commonButtonBackground="unset"
        commonButtonPadding="12px"
        commonButtonWidth="202px"
        commonButtonFilter="drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25))"
        buttonColor="unset"
        buttonMinWidth="unset"
        buttonFlex="1"
        buttonBackground="linear-gradient(#2eff1b, #2eff1b), linear-gradient(#2335fd, #2335fd), #2335fd"
        buttonWebkitBackgroundClip="unset"
        buttonWebkitTextFillColor="unset"
      />
      <div className={styles.duplicateCards}>
        <div className={styles.duplicateHeader}>
          <AboutHeader />
        </div>
        <div className={styles.cardGrid}>
          <div className={styles.card2Parent}>
            <Card
              propFlex="unset"
              propAlignSelf="stretch"
              propWidth="unset"
              propMarginLeft="unset"
              propMarginBottom="unset"
              propHeight="unset"
              propPadding="unset"
              propHeight1="unset"
              propMinWidth="177px"
              propPadding1="0px 0px 0px 0px"
              propAlignSelf1="unset"
              titleGoesHere="FAULT REPORTING"
              propAlignSelf2="unset"
              propFlex1="unset"
              secondaryText="Document every fault"
              propHeight2="unset"
              propDisplay="unset"
              propAlignSelf3="stretch"
              rectangle18="/rectangle-18-1@2x.png"
              propFlex2="unset"
              propFlex3="unset"
              loremIpsumDolorSitAmetConsecte="Enable quick and accurate reporting of equipment issues by medical staff, ensuring timely intervention and minimizing downtime for essential medical tools"
              propAlignSelf4="unset"
              button="Report fault"
            />
            <Card
              propFlex="unset"
              propAlignSelf="unset"
              propWidth="354px"
              propMarginLeft="unset"
              propMarginBottom="unset"
              propHeight="unset"
              propPadding="unset"
              propHeight1="unset"
              propMinWidth="162px"
              propPadding1="unset"
              propAlignSelf1="unset"
              titleGoesHere="PPM FORM"
              propAlignSelf2="stretch"
              propFlex1="unset"
              secondaryText="Document every work"
              propHeight2="unset"
              propDisplay="unset"
              propAlignSelf3="stretch"
              rectangle18="/rectangle-18-2@2x.png"
              propFlex2="unset"
              propFlex3="unset"
              loremIpsumDolorSitAmetConsecte="Schedule and record regular maintenance activities to prevent equipment failures, extending the lifespan of devices and ensuring consistent performance."
              propAlignSelf4="unset"
              button="Record"
              commonButtonBoxShadow="unset"
              commonButtonBackground="unset"
              commonButtonPadding="12px"
              commonButtonWidth="202px"
              commonButtonFilter="drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25))"
              buttonColor="unset"
              buttonMinWidth="unset"
              buttonFlex="1"
              buttonBackground="linear-gradient(#2eff1b, #2eff1b), linear-gradient(#2335fd, #2335fd), #2335fd"
              buttonWebkitBackgroundClip="unset"
              buttonWebkitTextFillColor="unset"
            />
          </div>
          <FrameComponent
            titleGoesHere="JOB CARD"
            titleGoesHere1="Daily Routine"
            secondaryText="Document every step"
            secondaryText1="Document every day’s work"
            rectangle18="/rectangle-18@2x.png"
            rectangle181="/rectangle-18-4@2x.png"
            loremIpsumDolorSitAmetConsecte="Document and monitor all maintenance and repair tasks, promoting accountability, timely action, and continuous operation of critical medical equipment.."
            loremIpsumDolorSitAmetConsecte1="Log daily maintenance activities and routine checks, ensuring ongoing equipment reliability and addressing minor issues before they escalate."
            propFlex="unset"
            propFlex1="1"
            propAlignSelf="stretch"
            propAlignSelf1="unset"
            propWidth="unset"
            propWidth1="unset"
            propMarginLeft="unset"
            propMarginLeft1="unset"
            propMarginBottom="unset"
            propMarginBottom1="unset"
            propHeight="unset"
            propHeight1="unset"
            propPadding1="unset"
            propPadding2="0px 0px 20px"
            propHeight11="unset"
            propHeight12="unset"
            propMinWidth="162px"
            propMinWidth1="162px"
            propPadding11="unset"
            propPadding12="0px 0px 0px 0px"
            propAlignSelf11="unset"
            propAlignSelf12="unset"
            propAlignSelf2="stretch"
            propAlignSelf21="stretch"
            propFlex11="unset"
            propFlex12="unset"
            propHeight2="unset"
            propHeight21="unset"
            propDisplay="unset"
            propDisplay1="unset"
            propAlignSelf3="stretch"
            propAlignSelf31="unset"
            propFlex2="unset"
            propFlex21="unset"
            propFlex3="unset"
            propFlex31="unset"
            propAlignSelf4="unset"
            propAlignSelf41="unset"
          />
          <FrameComponent
            propPadding="unset"
            titleGoesHere="INVENTORY"
            titleGoesHere1="REPORTS"
            secondaryText="Document every asset"
            secondaryText1="Generate reports"
            rectangle18="/rectangle-18-5@2x.png"
            rectangle181="/rectangle-18-6@2x.png"
            loremIpsumDolorSitAmetConsecte="Efficiently manage and track all medical equipment, ensuring readiness, proper maintenance scheduling, and compliance with asset management protocols at your Hospital."
            loremIpsumDolorSitAmetConsecte1="Create  reports on equipment status, maintenance activities, and fault resolutions, providing valuable insights for decision-making, compliance, and improving hospital operations."
            propFlex="unset"
            propAlignSelf="unset"
            propWidth="354px"
            propMarginLeft="unset"
            propMarginBottom="unset"
            propHeight="unset"
            propPadding1="unset"
            propHeight11="unset"
            propMinWidth="162px"
            propPadding11="unset"
            propAlignSelf11="unset"
            propAlignSelf2="stretch"
            propFlex11="unset"
            propHeight2="unset"
            propDisplay="unset"
            propAlignSelf3="stretch"
            propFlex2="unset"
            propFlex3="unset"
            propAlignSelf4="unset"
          />
        </div>
      </div>
    </section>
  );
};

export default CardsContainer;
